#!/bin/sh

# this is a wrapper script, to avoid running the linux version when under X
# when there is a wayland client.. also examine WAYLAND_DISPLAY

if [ -z "$DISPLAY" ]; then
  mmm.linux $*
else
  mmm.sdl $*
fi
